sudo: required
language: go

go:
  - master
  - 1.8.x

script: make test

# TODO (Karun): This works only if travis has k8s environment. Hence commenting it for now.
#install:
#    - go get -v github.com/onsi/ginkgo/ginkgo
#    - go get -v github.com/onsi/gomega
#    - export PATH=$PATH:$HOME/gopath/bin

# TODO (Karun): This works only if travis has k8s environment. Hence commenting it for now.
# script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

services:
  - docker

env:
  global:

after_success:
  - docker --version
  - echo 'Travis commit is:\n'
  - echo $TRAVIS_COMMIT
  - echo 'Travis Build Number is:\n'
  - echo $TRAVIS_BUILD_NUMBER
  - echo $DOCKER_USERNAME
  - echo $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
